# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='content',
        ),
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static/documents/'),
            preserve_default=False,
        ),
    ]
