# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180222_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
