# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20180225_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
