# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_auto_20180225_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='image',
        ),
    ]
